# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Put host-level changes
# in hosts/thinkpad/default.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b6585b8d-fe2a-46f8-9146-6126d3665f76";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b6585b8d-fe2a-46f8-9146-6126d3665f76".device = "/dev/disk/by-uuid/b6585b8d-fe2a-46f8-9146-6126d3665f76";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6ABD-33DB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
